# Generated by Django 5.2.5 on 2025-10-07 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("acct_num", models.TextField(blank=True)),
                ("value", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("General", "General"),
                            ("Cash", "Cash"),
                            ("Current", "Current"),
                            ("Current account", "Current account"),
                            ("Credit card", "Credit card"),
                            ("Saving account", "Saving account"),
                            ("Investment", "Investment"),
                            ("Insurance", "Insurance"),
                            ("Bonus", "Bonus"),
                            ("Loan", "Loan"),
                            ("Mortgage", "Mortgage"),
                        ],
                        max_length=50,
                    ),
                ),
                ("currency", models.CharField(max_length=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
