# Generated by Django 5.2.5 on 2025-10-07 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("private", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "record_type",
                    models.CharField(
                        choices=[
                            ("income", "Income"),
                            ("expense", "Expense"),
                            ("transfer", "Transfer"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Food & Drinks", "Food & Drinks"),
                            ("Shopping", "Shopping"),
                            ("Housing", "Housing"),
                            ("Transportation", "Transportation"),
                            ("Vehicle", "Vehicle"),
                            ("Life & Entertainment", "Life & Entertainment"),
                            ("Communication, PC", "Communication, PC"),
                            ("Financial expenses", "Financial expenses"),
                            ("Investments", "Investments"),
                            ("Income", "Income"),
                            ("Others", "Others"),
                        ],
                        max_length=100,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("note", models.TextField(blank=True)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="private.account",
                    ),
                ),
            ],
        ),
    ]
