# Generated by Django 5.2.5 on 2025-10-08 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("private", "0002_record"),
    ]

    operations = [
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("target_amt", models.DecimalField(decimal_places=2, max_digits=12)),
                ("saved_amt", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "save_goal",
                    models.CharField(
                        choices=[
                            ("new_vehicle", "New Vehicle"),
                            ("new_home", "New Home"),
                            ("holiday_trip", "Holiday Trip"),
                            ("health_care", "Health Care"),
                            ("education", "Education"),
                            ("emergency_fund", "Emergency Fund"),
                            ("party", "Party"),
                            ("kidspoiling", "Kid Spoiling"),
                            ("charity", "Charity"),
                            ("other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                ("desire_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Food & Drinks", "Food & Drinks"),
                            ("Shopping", "Shopping"),
                            ("Housing", "Housing"),
                            ("Transportation", "Transportation"),
                            ("Vehicle", "Vehicle"),
                            ("Life & Entertainment", "Life & Entertainment"),
                            ("Communication, PC", "Communication, PC"),
                            ("Financial expenses", "Financial expenses"),
                            ("Investments", "Investments"),
                            ("Income", "Income"),
                            ("Others", "Others"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("None", "None"),
                            ("Week", "Week"),
                            ("Year", "Year"),
                            ("One_Time", "One Time"),
                        ],
                        max_length=100,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(max_length=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("account", models.ManyToManyField(to="private.account")),
            ],
        ),
        migrations.CreateModel(
            name="Debt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("person", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "debt_type",
                    models.CharField(
                        choices=[("borrowed", "I borrowed"), ("lent", "I lent")],
                        max_length=100,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("start_date", models.DateField()),
                ("due_date", models.DateField()),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="private.account",
                    ),
                ),
            ],
        ),
    ]
