# Generated by Django 5.2.5 on 2025-10-08 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("private", "0003_goal_budget_debt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="value",
            new_name="balance",
        ),
        migrations.AddField(
            model_name="account",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="record",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="acct_num",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["user", "created_at"], name="private_acc_user_id_a5a845_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="record",
            index=models.Index(
                fields=["user", "date"], name="private_rec_user_id_17fe7f_idx"
            ),
        ),
    ]
