# Generated by Django 5.2.5 on 2025-10-20 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("private", "0005_record_from_account_record_is_recurring_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="account",
            name="unique_account_per_user",
        ),
        migrations.RemoveIndex(
            model_name="account",
            name="private_acc_user_id_a5a845_idx",
        ),
    ]
