# Generated by Django 5.2.5 on 2025-10-20 19:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("private", "0006_remove_account_unique_account_per_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="unique_account_per_user"
            ),
        ),
    ]
