# Generated by Django 5.2.5 on 2025-10-21 15:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("private", "0007_account_unique_account_per_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="private.account",
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="record",
            name="time",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
