# Generated by Django 5.2.5 on 2025-10-22 09:27

import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("private", "0008_alter_record_account_alter_record_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="budget",
            name="category",
        ),
        migrations.AddField(
            model_name="budget",
            name="categories",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("Salary", "Salary"),
                    ("Freelance", "Freelance"),
                    ("Investments", "Investments"),
                    ("Rental Income", "Rental Income"),
                    ("Gifts", "Gifts"),
                    ("Refunds", "Refunds"),
                    ("Other Income", "Other Income"),
                    ("Food & Drinks", "Food & Drinks"),
                    ("Groceries", "Groceries"),
                    ("Dining Out", "Dining Out"),
                    ("Shopping", "Shopping"),
                    ("Housing", "Housing"),
                    ("Utilities", "Utilities"),
                    ("Transportation", "Transportation"),
                    ("Vehicle", "Vehicle"),
                    ("Life & Entertainment", "Life & Entertainment"),
                    ("Communication, PC", "Communication, PC"),
                    ("Financial expenses", "Financial expenses"),
                    ("Health & Medical", "Health & Medical"),
                    ("Education", "Education"),
                    ("Insurance", "Insurance"),
                    ("Travel", "Travel"),
                    ("Gifts & Donations", "Gifts & Donations"),
                    ("Personal Care", "Personal Care"),
                    ("Subscriptions", "Subscriptions"),
                    ("Taxes", "Taxes"),
                    ("Savings", "Savings"),
                    ("Pets", "Pets"),
                    ("Childcare", "Childcare"),
                    ("Hobbies", "Hobbies"),
                    ("Debt & Loans", "Debt & Loans"),
                    ("Repairs & Maintenance", "Repairs & Maintenance"),
                    ("Electronics", "Electronics"),
                    ("Clothing & Apparel", "Clothing & Apparel"),
                    ("Beauty & Wellness", "Beauty & Wellness"),
                    ("Books & Media", "Books & Media"),
                    ("Office Supplies", "Office Supplies"),
                    ("Gardening", "Gardening"),
                    ("Sports & Fitness", "Sports & Fitness"),
                    ("Weddings & Events", "Weddings & Events"),
                    ("Household Supplies", "Household Supplies"),
                    ("Legal Fees", "Legal Fees"),
                    ("Charity", "Charity"),
                    ("Business Expenses", "Business Expenses"),
                    ("Others", "Others"),
                ],
                default=list,
                max_length=561,
                verbose_name="Category",
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="budget",
            name="period",
            field=models.CharField(
                choices=[
                    ("Week", "Week"),
                    ("Month", "Month"),
                    ("Year", "Year"),
                    ("One-Time", "One Time"),
                ],
                max_length=100,
            ),
        ),
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(
                fields=["user", "start_date"], name="private_bud_user_id_65164f_idx"
            ),
        ),
    ]
