# Generated by Django 5.2.5 on 2025-10-23 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "private",
            "0009_remove_budget_category_budget_categories_budget_user_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="goal",
            old_name="save_goal",
            new_name="goal_name",
        ),
        migrations.RenameField(
            model_name="goal",
            old_name="saved_amt",
            new_name="target_amount",
        ),
        migrations.RenameField(
            model_name="goal",
            old_name="desire_date",
            new_name="target_date",
        ),
        migrations.RemoveField(
            model_name="goal",
            name="name",
        ),
        migrations.RemoveField(
            model_name="goal",
            name="target_amt",
        ),
        migrations.AddField(
            model_name="goal",
            name="note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="goal",
            name="saved_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="goal",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
